version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432" # Exposes PostgreSQL on localhost:5432
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379" # Exposes Redis on localhost:6379

  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodeapp
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app  # Maps your local code to the container
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
